name: Feature Request
description: Suggest an idea or enhancement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: What and Why
      description: What is the feature and why is it useful
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Any references or notes
    validations:
      required: false
